package com.sdfteam.d3armory.service.util;

public enum EnumerationBuffs{
	FOCUSEDMIND,ANATOMY,
	ARCHERY,SHARPSHOOTER,STEADYAIM,
	GLASSECANNON,MAGICWEAPON,MAGICWEAPON_FORCEWEAPON,FAMILIAR_SPARK,ENERGYARMOR,PINPOINT,
	PIERCETHEVEIL,
	BREATHTHEHEAVEN,MANTRAOFRETRIBUTION_TRANSGRESSION,BLINDINGFLASH_FAITTHELIGHT,
	BERSERKERRAGE,BRAWLER,RUTHLESS,WEAPONMASTER,BATTLERAGE,BATTLERAGE_MARAUDER,WRATHOFTHEBERSERKER, WRATHOFTHEBERSERKER_INSANITY
}